"""empty message

Revision ID: 60a17df0e0bd
Revises: 835ff706a25f
Create Date: 2022-08-14 11:21:58.350291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60a17df0e0bd'
down_revision = '835ff706a25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tingkat_aktivitas_ibfk_1', 'tingkat_aktivitas', type_='foreignkey')
    op.create_foreign_key(None, 'tingkat_aktivitas', 'gender', ['gender'], ['name'], ondelete='SET NULL')
    op.drop_constraint('user_ibfk_1', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'gender', ['gender'], ['name'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_1', 'user', 'gender', ['gender'], ['name'])
    op.drop_constraint(None, 'tingkat_aktivitas', type_='foreignkey')
    op.create_foreign_key('tingkat_aktivitas_ibfk_1', 'tingkat_aktivitas', 'gender', ['gender'], ['name'])
    # ### end Alembic commands ###
