"""empty message

Revision ID: 70fc464428ee
Revises: 63d6749ebb20
Create Date: 2022-08-12 17:26:38.539939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fc464428ee'
down_revision = '63d6749ebb20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tingkat_aktivitas', sa.Column('gender', sa.Enum('p', 'l', name='genderenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tingkat_aktivitas', 'gender')
    # ### end Alembic commands ###
